### ISSUE TITLE
In Chromium/Blink based browsers blurred image preview is rendered as a grey square due to CORS cache handling

### ISSUE THREAD

**Issue by phocks** [abcnews/odyssey#5]
This issue is related to this bug (which the Chromium team won't fix for some reason):

https://www.hacksoft.io/blog/handle-images-cors-error-in-chrome

To reproduce, open [this article](https://www.abc.net.au/news/2022-11-30/covid-pandemic-three-years-change-photo-journalism/101615726) in Chrome (or any Odyssey that has images in it) and scroll down fast. Open your browser console and make sure "disable cache" isn't checked in the network tab, then in the console you should see a number of CORS errors and you'll see grey rectangles instead of blurred image previews like you do in Firefox or Safari.

This is apparently because of the way Chrome (incorrectly) stores images in the cache without the cross-origin headers so when it goes to fetch them we get this error and the whole thing breaks.

A solution is to add a GET tag with the current unix time to the end of the img src URL so it forces the browser to fetch the image again, but this is not ideal as it should just use the cached version and not throw an error.

This could _possibly_ be solved on the server end too by setting the correct `Access-Control-Allow-Origin` if it isn't already being set correctly on this domain `live-production.wcms.abc-cdn.net.au`

**Comment by drzax** [comment]
Some additional context: The [ticket](https://bugs.chromium.org/p/chromium/issues/detail?id=409090) the Chromium maintainers closed as 'won't fix' makes the argument that the browser's behaviour is correct and that it's the server that's doing the wrong thing by not including CORS headers in the response's [`vary` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Vary). 

The situation arises because the first request for the image *doesn't* require [CORS headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) because it doesn't have a [`crossorigin` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin) while the second request [does](https://github.com/abcnews/odyssey/blob/d900f8f15fb8e1f8d2c3e69bcbeae21ddc774550/src/app/components/Picture/blur.js#L63) (the attribute is required because it [gets drawn to a `canvas`](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image)). 

The browser then caches the first response (including the lack of `Access-Control-Allow-Origin` header, which the subsequent request requires) because the server has declared (via the `vary` header or lack thereof) that it will send the same response regardless of whether CORS headers are sent in the request or not. So the second request, which does send (and requires) CORS headers, gets the cached response that doesn't have them.

This seems like tortured logic bound to cause difficult to diagnose problems just like this because CORS is inherently hard to understand. But it is nevertheless a defensible position to take. 

This leaves us with two potential solutions:

**1. Fix the server response**

This is the 'correct' solution. I don't know if it's even possible, but it would require Akamai to respond with a `vary` header indicating to the browser that the response depends on CORS headers. That would allow the browser to cache the CORS enabled response separately.

**2. Vary the request in some way other than the CORS headers**

This is the fix suggested in the [HackSoft article](https://www.hacksoft.io/blog/handle-images-cors-error-in-chrome). I think this will ultimately have the same effect — a separately cached version of the image that includes CORS headers. They suggest adding a search param to the URL as an easy way to vary the request.

While this looks like heavy-handed cache busting, it's not actually. There's no need for the search param to by dynamic and vary for *every* request (like a timestamp, for example), only that it's different from any other non-CORS requests for the same image. So while it is, in a sense, cache busting, it's not doing anything more than a server response with a `vary` header in option 1 would do because it can be a static string.

**A final thought**

Another approach to fixing this issue might be to re-think how the blurred placeholders are done or even remove them. The current implementation means that for lazy loaded images we are sometimes more than doubling the bandwidth being used to load the image.

For example, when [this image](https://live-production.wcms.abc-cdn.net.au/ec01f5e34bb7f6d08b9224da0452b295?impolicy=wcms_crop_resize&cropH=2913&cropW=4369&xPos=0&yPos=0&width=862&height=575) is requested by the browser because it's in the DOM, Akamai responds with a relatively light `image/avif` file:

<img width="375" alt="image" src="https://user-images.githubusercontent.com/596563/234193606-8c581592-7731-4620-b0de-865ccd374e9b.png">

But when it's requested by JS for the purposes of adding a blurred placeholder image, it's an `image/jpeg` that's more than twice the weight:

<img width="452" alt="image" src="https://user-images.githubusercontent.com/596563/234193856-0db5d685-fbdb-4c4a-b3f2-11a9bbd90df9.png">

I don't know why the results of these two requests are so different, but in any case, it's probably not the best approach to blurred placeholders for lazy loaded images. Even if it was the exact same binary returned, but with cross origin headers, we'd still be loading the image twice. If the original cached response could be used, the approach would make sense, but it looks like it can't be.

**Comment by phocks** [comment]
I tested adding `&no-cache` to the url.

```
imgEl.crossOrigin = 'Anonymous';
imgEl.src = url + "&no-cache";
```

However I don't think this is a proper fix as it just triggers another external fetch and so we still have the grey boxes, then a split second of the blurred image, then the image.

We just need to get the external server to add the correct access-control-allow-origin I think and that should be it fixed. Not sure why it dropped off in the first place (if that's actually what happened).
