### ISSUE TITLE
Video doesn't play when no poster media

### ISSUE THREAD

**Issue by phocks** [abcnews/odyssey#98]
Odyssey errors if no media found and so video doesn't play.

https://github.com/abcnews/odyssey/blob/af7c4d04199f93862987dbb28938b1c9486b89a0/src/app/components/VideoPlayer/utils.js#L6-L8

`Uncaught TypeError: Cannot read properties of undefined (reading 'image')`

Either wrap in try catch and return null if there is an error, or else check if item.media is undefined and then return null.

**Comment by drzax** [comment]
It actually would have been fine, I think, but 129164a6d82dfff8cf73fcb517c853584cdcc544 now further guards against missing poster.

The root cause of the issue was actually a DOM structure change that put a download link inside PL video elements. Odyssey was picking the (incorrect) video ID from the download link anchor's href. This prioritises a different element 
ab9255527fb4c2403419fda9df7789273191d399 and fixes the bug.
